// x86DASM.idl : type library source for x86DASM.exe

// This file will be processed by the MIDL compiler to produce the
// type library (x86DASM.tlb).

[ uuid(B4208A14-DD85-402F-984A-15CB583B74B4), version(1.0) ]
library x86DASM
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for Cx86DASMDoc
	
	[ uuid(EA876594-F680-4C42-A46F-5FAFF4955832) ]
	dispinterface Ix86DASM
	{
		properties:
			
		methods:
	};

	//  Class information for Cx86DASMDoc
	
	[ uuid(93C1A70C-95B6-4DFC-BCED-D8EB97D94F69) ]
	coclass Cx86DASMDoc
	{
		[default] dispinterface Ix86DASM;
	};
};
