// Decipher.idl : type library source for Decipher.exe

// This file will be processed by the MIDL compiler to produce the
// type library (Decipher.tlb).

[ uuid(0E0F69AA-2971-44E3-9EDD-D8ECDE18FB17), version(1.0) ]
library Decipher
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for CDecipherDoc
	
	[ uuid(7A535ACA-EEB6-4A90-89B8-30F9BB0BC787) ]
	dispinterface IDecipher
	{
		properties:
			
		methods:
	};

	//  Class information for CDecipherDoc
	
	[ uuid(166E0410-AEF9-4E8C-BEB4-AA845327888E) ]
	coclass Decipher
	{
		[default] dispinterface IDecipher;
	};
};
